[smartmodule] changes in Makefile and System Status.
mayaculpa/hapi pull request #129
Opened 2017-12-20 12:35 UTC by PedroSFreitas

Attention: this PR should be review in order to evaluate if the changes are desirable. These changes was proposed by me back in July, 2017 so I'm not sure if they are a good fit for **now**. Maybe the direction of the project has changed and these are no longer necessary.

Makefile: adding `help` and `usage`.

smart_module.py: silly attempt to avoid unnecessary code for now, in a way to determine the memory leak as said in #60. And switching the return memory information as KBytes, rather than Bytes.

2017-12-20 12:37 UTC, PedroSFreitas commented
@TylerReedMC @moritz89 

Glad to see the project is now coming back. As I always have said, this is a great project and with some hard work and time, should help a lot of people around the world.

I believe the commit messages are very informative about the changes but I have expressed a few more things in the PR message area. I'm at your disposal for further information, please feel free to contact me.

2017-12-21 08:57 UTC, moritz89 requested changes
The addition of usage info in make is useful and the use of KBytes makes things more human friendly.

Could you add the order in which the make commands have to be executed in the readme (src/smart-module/README.md)? A short list would simplify the installation process

2017-12-23 16:36 UTC, PedroSFreitas commented
@moritz89 README added.
Please, I kindly suggest a review of the file since English isn't my native language. :) 

At disposal for further request.
Cheers.

2017-12-24 12:43 UTC, moritz89 approved these changes

2017-12-24 12:44 UTC, merged